server:
  port: 6060

spring:
  profiles:
    active: Dev

---
spring:
  profiles: Dev
  datasource:
    url: jdbc:h2:mem:website
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      path: /h2-console
      enabled: true

---
spring:
  datasource:
    url: jdbc:h2:mem:website
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      path: /h2-console
      enabled: true